
name: Daily Telegram Bot

on:
  schedule:
    - cron: '30 6 * * *' # 6:30 UTC = 9:30 Asia/Riyadh (GMT+3)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot (Pro)
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          # Optionally override assets:
          # ASSETS: 'GC=F,CL=F,BTC-USD,^GSPC,EURUSD=X,TASI.SR'
        run: |
          python main.py
